config/routes.rb
Rails.application.routes.draw do
  root "dashboards#index"

  resources :dashboards
  resources :users do 
    post :assign_nfc
    collection do 
      post :check_access
    end
  end
  resources :access_logs
  resources :gates
  resources :roles do 
    post :add_gate
    post :remove_gate
  end
  resources :sessions do 
    collection do 
      get :logout
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/access_log.rb
class AccessLog < ApplicationRecord
  belongs_to :user
  belongs_to :gate
  belongs_to :nfc

  scope :today, -> { where(created_at: Time.zone.now.all_day)}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gate.rb
class Gate < ApplicationRecord
  before_create :generate_gate_serial 

  private 

  def generate_gate_serial
    self.serial_number = Digest::SHA1.hexdigest("#{id}_#{Time.current}")
  end
end

app/models/gate_permission.rb
class GatePermission < ApplicationRecord
  belongs_to :gate
end

app/models/nfc.rb
class Nfc < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :gate_permissions
	belongs_to :user, optional: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
	has_many :user_sessions
	belongs_to :role, optional: true
	has_many :nfcs
	has_many :access_logs
	
	has_secure_password

	validates :username, :password, presence: true
	validates :username, uniqueness: true
	validates :username, length: { minimum: 5, maximum: 20 }
	validates :password, length: { minimum: 5, maximum: 50 }
end
  

app/models/user_session.rb
class UserSession < ApplicationRecord
  belongs_to :user

  TOKEN_EXPIRE_AFTER = 1.hour

  before_create :generate_token

  def active?
    valid_at >= Time.current
  end

  def expired?
    !active?
  end

  def update_expiration
    update valid_at: expire_time
  end

  private

  def generate_token
    self.token = Digest::SHA1.hexdigest("#{id}_#{Time.current}")
    self.valid_at = expire_time
  end

  def expire_time
    Time.current + TOKEN_EXPIRE_AFTER
  end
end

app/controllers/access_logs_controller.rb
class AccessLogsController < ApplicationController
  def index 
    @access_logs = AccessLog.all.order(id: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, if: :json_request?

  attr_reader :current_admin

  def must_be_authenticated
    token = UserSession.find_by_token session[:token]
    if token.nil?
      session.clear
      redirect_to sessions_path
    else
      @current_admin = token.user
    end
  end
  
  private

  def json_request?
    request.format.json?
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :must_be_authenticated
  
  def index 
  end
end

app/controllers/gates_controller.rb
class GatesController < ApplicationController
  before_action :must_be_authenticated
  
  def index 
    @gates = Gate.all
  end

  def show 
    @gate = Gate.find(params[:id])
    qr_code = RQRCode::QRCode.new(@gate.serial_number, size: 4, level: :m)
    @qr_code_svg = qr_code.as_svg
  end

  def new
  end

  def create 
    Gate.create gate_params
    redirect_to gates_path
  end

  private 

  def gate_params 
    params.permit(:name)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :must_be_authenticated
  
  def index 
    @roles = Role.all
  end

  def show 
    @role = Role.find(params[:id])
    gate_ids = @role.gate_permissions.pluck(:gate_id)
    @gates = Gate.where.not(id: gate_ids)
  end

  def remove_gate 
    role = Role.find(params[:role_id])
    role.gate_permissions.find_by_id(params[:gate_permission_id]).delete
    redirect_to role_path(role)
  end

  def add_gate
    role = Role.find(params[:role_id])
    gate = role.gate_permissions.create({gate_id: params[:gate_id]})
    redirect_to role_path(role)
  end

  def create 
    p "+=="
    p role_params
    p "+=="
    Role.create role_params
    redirect_to roles_path
  end

  private 

  def role_params 
    params.permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    redirect_to root_path if session[:token].present?
  end

  def logout
    session.clear
    redirect_to root_path
  end

  def create
    admin = User.where(username: params[:username]).last
    if admin.present?
      if admin.authenticate params[:password]
        admin_session = admin.user_sessions.create
        session[:token] = admin_session.token
        redirect_to root_path
      else
        flash.alert = 'Invalid Account'
        redirect_to sessions_path
      end
    else
      flash.alert = 'Invalid Account'
      redirect_to sessions_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :must_be_authenticated, unless: :json_request?
	
	def new
	end
	
	def index
		@users = User.all
    respond_to do |format|
      format.html # Render the HTML view (default behavior)
      format.json { render json: { users: @users } }
    end
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		User.create user_params
		
		redirect_to users_path
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_columns(**user_update_params)
			redirect_to users_path
		end
	end

	def assign_nfc 
		user = User.find(params[:user_id])
		tags = Nfc.where(tag: params[:tag])
		if tags.present? 
			render json: {message: "Tag is already assigned"}
		else
			user.nfcs.create tag: params[:tag]
			render json: {message: "Tag assigned"}
		end
	end

	def check_access 
		nfc_tag = params[:nfc_tag]
		gate_serial = params[:gate_serial]

		# validation process 
		nfc = Nfc.find_by_tag(nfc_tag)
		gate = Gate.find_by_serial_number(gate_serial)
		if gate.nil? || nfc.nil?
			render json: {message: :denied}, status: 400
		else
			if nfc.user.present?
				access = nfc.user.role.gate_permissions.where(gate_id: gate.id)
				if access.any? 

					if(gate.name == "Main")
						main_gates =  nfc.user.access_logs.today.where(gate_id: gate.id)
						if main_gates.any?
							if main_gates.count % 2 == 0
								render json: {message: "logout.mp3"}
							else
								render json: {message: "login.mp3"}	
							end
						else
							render json: {message: "login.mp3"}
						end
					else
						render json: {message: "access-confirm.mp3"}
					end
					nfc.user.access_logs.create({nfc_id: nfc.id, gate_id: gate.id, is_access: true})
				else
					nfc.user.access_logs.create({nfc_id: nfc.id, gate_id: gate.id, is_access: false})
					render json: {message: "access-denied.mp3"}, status: 400
				end
			else
				render json: {message: "access-denied.mp3"}, status: 400
			end
		end
	end
	private

	def user_params
		params.permit( %i[first_name last_name email role_id device_id username password] )
	end

	def user_update_params
		params.permit( %i[first_name last_name email role_id device_id username disabled] )
	end
end

app/helpers/access_logs_helper.rb
module AccessLogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access_logs/index.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3>Access Logs</h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active">Access Logs</li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-body">
                  <table class="table table-bordered">
                    <thead>
                      <th>ID</th>
                      <th>USER</th>
                      <th>GATE</th>
                      <th>NFC</th>
                      <th>PERMITTED</th>
                      <th>TIME</th>
                    </thead>
                    <tbody>
                      <% @access_logs.each do |log|%>
                        <tr>
                          <td><%=log.id%></td>
                          <td><%="#{log.user.first_name} #{log.user.last_name}"%></td>
                          <td><%=log.gate.name%></td>
                          <td><%=log.nfc.tag%></td>
                          <td><%=log.is_access%></td>
                          <td><%=log.created_at.in_time_zone('Asia/Manila')%></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

app/views/dashboards/index.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper p-3">
    <div class="row">
        <div class="col-lg-3 col-6">
            <div class="small-box bg-info">
            <div class="inner">
                <h3><%=User.count%></h3>
                <p>Total Users</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-6">
            <div class="small-box bg-success">
                <div class="inner">
                    <h3><%=Gate.count%></h3>
                    <p>Total Gates</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-6">

            <div class="small-box bg-warning">
                <div class="inner">
                    <h3><%=Role.count%></h3>
                    <p>Total Roles</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-6">
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>0</h3>
                    <p>Logs</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>
</div>

app/views/gates/index.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3>Add Gates</h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active">Gates</li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header text-right">
                  <%= link_to new_gate_path do %>
                    <button class="btn btn-primary btn-sm">Add Gates</button>
                  <% end %>
                </div>
                <div class="card-body p-0">
                  <table class="table table-bordered">
                    <thead>
                      <th>ID</th>
                      <th>ID</th>
                      <th>ID</th>
                    </thead>
                    <tbody>
                      <% @gates.each do |gate|%>
                        <tr>
                          <td><%=gate.id%></td>
                          <td>
                            <%= link_to gate.name, gate_path(gate) %>
                          </td>
                          <td><%=gate.serial_number%></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

app/views/gates/new.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3>Add Gates</h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active"><%=link_to :Gates, gates_path%></li>
                      <li class="breadcrumb-item active">New</li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-6">
              <div class="card">
                <div class="card-body">
                  <%=form_tag (gates_path) do %>
                    <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example1">Name</label>
                        <%=text_field_tag :name, params[:name], class:'form-control', type:'text'%>
                    </div>
                    <%= submit_tag("Create", :class=>"btn btn-primary btn-block mb-4", :name=>"submit") %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

app/views/gates/show.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3><%=@gate.name%></h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active"><%=link_to :Gates, gates_path%></li>
                      <li class="breadcrumb-item active"><%=@gate.id%></li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-6">
              <div class="card">
                <div class="card-body text-center">
                  <%= raw @qr_code_svg %>
                  <%=@gate.serial_number%>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

app/views/roles/index.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3>Roles</h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active">Roles</li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header text-right">
                  <%= link_to new_role_path do %>
                    <button class="btn btn-primary btn-sm">Add Role</button>
                  <% end %>
                </div>
                <div class="card-body p-0">
                  <table class="table table-bordered">
                    <thead>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Is Active</th>
                    </thead>
                    <tbody>
                      <% @roles.each do |role|%>
                        <tr>
                          <td><%=role.id%></td>
                          <td>
                            <%=link_to role.name, role_path(role)%>
                          </td>
                          <td><%=role.is_active%></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

app/views/roles/new.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3>New Role</h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active"><%=link_to :Roles, roles_path%></li>
                      <li class="breadcrumb-item active">New</li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-6">
              <div class="card">
                <div class="card-body">
                  <%=form_tag (roles_path) do %>
                    <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example1">Name</label>
                        <%=text_field_tag :name, params[:name], class:'form-control', type:'text'%>
                    </div>
                    <%= submit_tag("Create", :class=>"btn btn-primary btn-block mb-4", :name=>"submit") %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

app/views/roles/show.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3><%=@role.name%></h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active"><%=link_to :Roles, roles_path%></li>
                      <li class="breadcrumb-item active"><%=@role.id%></li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-6">
              <div class="card">
                <div class="card-header"> 
                  Gate Access
                </div>
                <div class="card-body">
                  <% if @role.gate_permissions.any?%>
                    <table class="table table-bordered">
                      <thead>
                        <th>ID</th>
                        <th>GATE ID</th>
                        <th>#</th>
                      </thead>
                      <% @role.gate_permissions.each do |pem|%>
                        <tr>
                          <td><%=pem.id%></td>
                          <td><%=pem.gate.name%></td>
                          <td width="100">
                            <%=form_tag role_remove_gate_path(@role) do %>
                              <%= hidden_field_tag :gate_permission_id, pem.id %>
                              <%= submit_tag("Remove", :class=>"btn btn-danger btn-sm", :name=>"Remove") %>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </table>
                  <% else %>
                    <p>No Permission</p>
                  <% end %>
                </div>
              </div>
            </div>
            <% if @gates.any?%>
              <div class="col-6">
                <div class="card">
                  <div class="card-header"> 
                    Add Access
                  </div>
                  <div class="card-body">
                    <%=form_tag role_add_gate_path(@role) do %>
                        <div class="input-group mb-3">
                          <%= select_tag :gate_id, options_for_select(@gates.collect { |r| [r.name, r.id] }), class: "form-control" %>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <%= submit_tag("Add", :class=>"btn btn-primary btn-block mb-4", :name=>"submit") %>
                            </div>
                        </div>
                    <% end %>
                  </div>
                </div>
              </div>    
            <% end %>
        </div>
      </div>
    </section>
</div>

app/views/users/edit.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
  <section class="content-header">    
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <h3>Update User</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
            <li class="breadcrumb-item active"><%=link_to :Users, users_path%></li>
            <li class="breadcrumb-item active">New</li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <%= form_tag user_path(@user), :method => :put do %>
                <div class="form-outline mb-4 col-3">
                  <label class="form-label mt-3" for="first_name">First Name</label>
                  <%=text_field_tag :first_name, @user.first_name, class:'form-control', type:'text'%>
                  <label class="form-label mt-3" for="last_name">Last Name</label>
                  <%=text_field_tag :last_name, @user.last_name, class:'form-control', type:'text'%>
                    <label class="form-label mt-3" for="email">Email</label>
                  <%=text_field_tag :email, @user.email, class:'form-control', type:'text'%>
                  <label class="form-label mt-3" for="role_id">Role</label>
                  <%# <%= select_tag(:role_id, options_for_select(Role.all.collect { |t| [t.name, t.id]}), class:"select form-control")%>
                  <%= select_tag(:role_id, options_for_select(Role.all.collect { |r| [r.name, r.id] }, @user.role_id), class:"select form-control") %>
                  <%# <%=text_field_tag :row, params[:name], class:'form-control', type:'text'%>
                  <label class="form-label mt-3" for="username">Username</label>
                  <%=text_field_tag :username, @user.username, class:'form-control', type:'text'%>
                  <label class="form-label mt-3" for="password">Disabled</label> 
                  <div class="checkbox">
                    <td>
                      <%= check_box_tag 'disabled', 1,  @user.disabled %>
                    </td>
                  </div>
                </div>
                <%= submit_tag("Update", :class=>"btn btn-primary btn-block mb-4 ml-2 col-2", :name=>"submit") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/users/index.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
  <section class="content-header">    
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h3>Users</h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                    <li class="breadcrumb-item">Users</li>
                </ol>
            </div>
        </div>
    </div>
  </section>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header text-right">
              <%= link_to new_user_path do %>
                    <button class="btn btn-primary btn-sm">Add Users</button>
                  <% end %>
            </div>
            <div class="card-body p-0">
              <table class="table table-bordered">
                <thead>
                  <th>ID</th>
                  <th>Username</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th></th>
                </thead>
                
                <tbody>
                  <% if @users%>
                    <% @users.each do |user|%>
                      <% if user.disabled %>
                        <tr class="table-secondary">
                      <% else %>
                        <tr>
                      <% end %>
                        <td><%=user.id%></td>
                        <td><%=user.username%></td>
                        <td><%=user.first_name%> <%=user.last_name%></td>
                        <td><%=user.email%></td>
                        <% if user.role_id%>
                          <td> <%= Role.all.find { |u| u.id == user.role_id }.name %> </td>
                        <% else %>
                          <td></td>
                        <% end %>
                        <td class="d-flex justify-content-center">
                          <%= link_to edit_user_path(user.id) do %>
                            <button class="btn btn-secondary btn-sm">Update</button>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  <% else %>
                    <tr>
                      <td>No records found</td>
                    </tr>
                  <% end %>
                  
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>  
  </section>
</div>

app/views/users/new.html.erb
<%= render 'shared/header'%>
<%= render 'shared/sidebar'%>
<div class="content-wrapper">
    <section class="content-header">    
      <div class="container-fluid">
          <div class="row">
              <div class="col-sm-6">
                  <h3>Add User</h3>
              </div>
              <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><%=link_to :Dashboard, root_path%></li>
                      <li class="breadcrumb-item active"><%=link_to :Users, users_path%></li>
                      <li class="breadcrumb-item active">New</li>
                  </ol>
              </div>
          </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-body">
                  <%=form_tag (users_path) do %>
                    <div class="form-outline mb-4 col-3">
                        <label class="form-label mt-3" for="first_name">First Name</label>
                        <%=text_field_tag :first_name, params[:first_name], class:'form-control', type:'text'%>
                        <label class="form-label mt-3" for="last_name">Last Name</label>
                        <%=text_field_tag :last_name, params[:last_name], class:'form-control', type:'text'%>
                         <label class="form-label mt-3" for="email">Email</label>
                        <%=text_field_tag :email, params[:email], class:'form-control', type:'text'%>
                        <label class="form-label mt-3" for="role_id">Role</label>
                        <%# <%= select_tag(:role_id, options_for_select(Role.all.collect { |t| [t.name, t.id]}), class:"select form-control")%>
                        <%= select_tag(:role_id, options_for_select(Role.all.collect { |r| [r.name, r.id] },params[:role_id] ), class:"select form-control") %>
                        <%# <%=text_field_tag :row, params[:name], class:'form-control', type:'text'%>
                        <label class="form-label mt-3" for="username">Username</label>
                        <%=text_field_tag :username, params[:username], class:'form-control', type:'text'%>
                        <label class="form-label mt-3" for="password">Password</label>
                        <%=text_field_tag :password, params[:password], class:'form-control', type:'text'%>
                    </div>
                    <%= submit_tag("Create", :class=>"btn btn-primary btn-block mb-4 ml-2 col-2", :name=>"submit") %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
</div>