config/routes.rb
Rails.application.routes.draw do
  root "dashboards#index"

  resources :dashboards
  resources :users do 
    post :assign_nfc
    collection do 
      post :check_access
    end
  end
  resources :access_logs
  resources :gates
  resources :roles do 
    post :add_gate
    post :remove_gate
  end
  resources :sessions do 
    collection do 
      get :logout
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/access_log.rb
class AccessLog < ApplicationRecord
  belongs_to :user
  belongs_to :gate
  belongs_to :nfc

  scope :today, -> { where(created_at: Time.zone.now.all_day)}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gate.rb
class Gate < ApplicationRecord
  before_create :generate_gate_serial 

  private 

  def generate_gate_serial
    self.serial_number = Digest::SHA1.hexdigest("#{id}_#{Time.current}")
  end
end

app/models/gate_permission.rb
class GatePermission < ApplicationRecord
  belongs_to :gate
end

app/models/nfc.rb
class Nfc < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :gate_permissions
	belongs_to :user, optional: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
	has_many :user_sessions
	belongs_to :role, optional: true
	has_many :nfcs
	has_many :access_logs
	
	has_secure_password

	validates :username, :password, presence: true
	validates :username, uniqueness: true
	validates :username, length: { minimum: 5, maximum: 20 }
	validates :password, length: { minimum: 5, maximum: 50 }
end
  

app/models/user_session.rb
class UserSession < ApplicationRecord
  belongs_to :user

  TOKEN_EXPIRE_AFTER = 1.hour

  before_create :generate_token

  def active?
    valid_at >= Time.current
  end

  def expired?
    !active?
  end

  def update_expiration
    update valid_at: expire_time
  end

  private

  def generate_token
    self.token = Digest::SHA1.hexdigest("#{id}_#{Time.current}")
    self.valid_at = expire_time
  end

  def expire_time
    Time.current + TOKEN_EXPIRE_AFTER
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :must_be_authenticated
  
  def index 
  end
end

app/controllers/gates_controller.rb
class GatesController < ApplicationController
  before_action :must_be_authenticated
  
  def index 
    @gates = Gate.all
  end

  def show 
    @gate = Gate.find(params[:id])
    qr_code = RQRCode::QRCode.new(@gate.serial_number, size: 4, level: :m)
    @qr_code_svg = qr_code.as_svg
  end

  def new
  end

  def create 
    Gate.create gate_params
    redirect_to gates_path
  end

  private 

  def gate_params 
    params.permit(:name)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :must_be_authenticated
  
  def index 
    @roles = Role.all
  end

  def show 
    @role = Role.find(params[:id])
    gate_ids = @role.gate_permissions.pluck(:gate_id)
    @gates = Gate.where.not(id: gate_ids)
  end

  def remove_gate 
    role = Role.find(params[:role_id])
    role.gate_permissions.find_by_id(params[:gate_permission_id]).delete
    redirect_to role_path(role)
  end

  def add_gate
    role = Role.find(params[:role_id])
    gate = role.gate_permissions.create({gate_id: params[:gate_id]})
    redirect_to role_path(role)
  end

  def create 
    p "+=="
    p role_params
    p "+=="
    Role.create role_params
    redirect_to roles_path
  end

  private 

  def role_params 
    params.permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    redirect_to root_path if session[:token].present?
  end

  def logout
    session.clear
    redirect_to root_path
  end

  def create
    admin = User.where(username: params[:username]).last
    if admin.present?
      if admin.authenticate params[:password]
        admin_session = admin.user_sessions.create
        session[:token] = admin_session.token
        redirect_to root_path
      else
        flash.alert = 'Invalid Account'
        redirect_to sessions_path
      end
    else
      flash.alert = 'Invalid Account'
      redirect_to sessions_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :must_be_authenticated, unless: :json_request?
	
	def new
	end
	
	def index
		@users = User.all
    respond_to do |format|
      format.html # Render the HTML view (default behavior)
      format.json { render json: { users: @users } }
    end
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		User.create user_params
		
		redirect_to users_path
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_columns(**user_update_params)
			redirect_to users_path
		end
	end

	def assign_nfc 
		user = User.find(params[:user_id])
		tags = Nfc.where(tag: params[:tag])
		if tags.present? 
			render json: {message: "Tag is already assigned"}
		else
			user.nfcs.create tag: params[:tag]
			render json: {message: "Tag assigned"}
		end
	end

	def check_access 
		nfc_tag = params[:nfc_tag]
		gate_serial = params[:gate_serial]

		# validation process 
		nfc = Nfc.find_by_tag(nfc_tag)
		gate = Gate.find_by_serial_number(gate_serial)
		if gate.nil? || nfc.nil?
			render json: {message: :denied}, status: 400
		else
			if nfc.user.present?
				access = nfc.user.role.gate_permissions.where(gate_id: gate.id)
				if access.any? 

					if(gate.name == "Main")
						main_gates =  nfc.user.access_logs.today.where(gate_id: gate.id)
						if main_gates.any?
							if main_gates.count % 2 == 0
								render json: {message: "logout.mp3"}
							else
								render json: {message: "login.mp3"}	
							end
						else
							render json: {message: "login.mp3"}
						end
					else
						render json: {message: "access-confirm.mp3"}
					end
					nfc.user.access_logs.create({nfc_id: nfc.id, gate_id: gate.id, is_access: true})
				else
					nfc.user.access_logs.create({nfc_id: nfc.id, gate_id: gate.id, is_access: false})
					render json: {message: "access-denied.mp3"}, status: 400
				end
			else
				render json: {message: "access-denied.mp3"}, status: 400
			end
		end
	end
	private

	def user_params
		params.permit( %i[first_name last_name email role_id device_id username password] )
	end

	def user_update_params
		params.permit( %i[first_name last_name email role_id device_id username disabled] )
	end
end

app/helpers/access_logs_helper.rb
module AccessLogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Likha-IT | Freee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="sidebar-mini layout-fixed">
    <div class="wrapper">
      <%= yield %>
    </div>  
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="/" class="nav-link">Dashboard</a>
    </li>
  </ul>
  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <%=link_to logout_sessions_path do %>
        <button class="btn btn-danger btn-sm">Logout</button>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%=link_to root_path, class:'brand-link' do %>
    <%= image_tag('logo.png', alt: 'Logo', size: '50') %>
    <span class="brand-text font-weight-light">Admin</span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar nav-child-indent flex-column" data-widget="treeview" role="menu" data-accordion="true">        
        <li class="nav-item has-treeview">
          <%=link_to users_path, class:(controller_name == 'users' ? 'nav-link active' : 'nav-link' ) do %>
            <i class="nav-icon fas fa-users"></i>
            <p>
              Users
              <i class="right fas fa-angle-right"></i>
            </p>
          <% end %> 
        </li>
        <li class="nav-item has-treeview">
          <%=link_to gates_path, class:(controller_name == 'gates' ? 'nav-link active' : 'nav-link' ) do %>
            <i class="nav-icon fas fa-sign-in"></i>
            <p>
              Gates
              <i class="right fas fa-angle-right"></i>
            </p>
          <% end %> 
        </li>
        <li class="nav-item has-treeview">
          <%=link_to roles_path, class:(controller_name == 'roles' ? 'nav-link active' : 'nav-link' ) do %>
            <i class="nav-icon fas fa-lock"></i>
            <p>
              Roles
              <i class="right fas fa-angle-right"></i>
            </p>
          <% end %> 
        </li>

        <li class="nav-item has-treeview">
          <%=link_to access_logs_path, class:(controller_name == 'access_logs' ? 'nav-link active' : 'nav-link' ) do %>
            <i class="nav-icon fas fa-history"></i>
            <p>
              Access Logs
              <i class="right fas fa-angle-right"></i>
            </p>
          <% end %> 
        </li>
        
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>